[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
hdi = "0.5.0-rc"
hdk = { version = "0.4.0-rc", features = [ "unstable-functions" ] }
serde = "1"

[patch.crates-io]
libmdns = { git = "https://github.com/guillemcordoba/libmdns", branch = "main" }
