name: "build-always-online-node"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-always-online-node:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-latest, macos-13]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Extend space
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: ./.github/actions/extend-space

      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.11

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v15
        with:
          name: darksoil-studio

      - name: Build always-online-node
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix watch-exec darksoil-studio -- nix build -L --accept-flake-config --no-update-lock-file .#always-online-node

      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2

      - name: Pin always-online-node
        if: github.event_name != 'pull_request'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix pin darksoil-studio always-online-node $(nix path-info --json --accept-flake-config --no-warn-dirty .#always-online-node | jq -r 'keys[0]')
